extends: airbnb
env:
  browser: true
plugins:
  - react
  - jsx-a11y
  - import
rules:
  class-methods-use-this:
    - off
  comma-dangle:
    - off
  no-bitwise:
    - error
    - allow:
      - '~'
  react/jsx-filename-extension:
    - off
parser: babel-eslint
