version: 2
jobs:
  build:
    docker:
      - image: node:7.7.3
    working_directory: ~/st2apidocs
    steps:
      - checkout
      - run:
          name: Fetch latest StackStorm OpenAPI spec
          command: |
            curl -SsL -q -o jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
            chmod +x ./jq
            BUILD_NUM="$(curl -Ss -q https://circleci.com/api/v1.1/project/github/StackStorm/st2 | ./jq -r ". | map(select(.branch == \"${ST2_GITREV:-$CIRCLE_BRANCH}\" and .outcome == \"success\")) | max_by(.build_num) | .build_num")"
            SPEC_URL="$(curl -Ss -q https://circleci.com/api/v1.1/project/github/StackStorm/st2/${BUILD_NUM}/artifacts | ./jq -r '.[].url' | grep openapi.yaml)"
            curl -Ss -q -o openapi.yaml ${SPEC_URL}
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Lint
          command: npm run lint --silent
      - run:
          name: Test
          command: npm test
      - run:
          name: Install doc generator
          command: npm install -g https://github.com/StackStorm/st2apidocgen
      - run:
          name: Generate API documentation
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              st2apidocgen --render --output
            else
              st2apidocgen --render /${CIRCLE_BUILD_NUM} --output
            fi
      - store_artifacts:
          path: ~/st2apidocs/build
          destination: build
      - deploy:
          name: Installing deploy dependencies
          command: |
            apt -y update && apt -y install python-pip
            pip install awscli==1.11.18
            aws configure set preview.cloudfront true
      - deploy:
          name: Deploying to S3
          command: |
            find ~/st2apidocs/build | sed 's|[^/]*/|  |g'
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync build/ s3://api.stackstorm.com/ --region ${REGION} --delete
              aws cloudfront create-invalidation --distribution-id=${DISTRIBUTION_ID} --paths="/*"
            else
              aws s3 sync build/ s3://api-staging.stackstorm.com/${CIRCLE_BUILD_NUM} --region ${REGION}
            fi
